services:
  simple_invites:
    image: bassdoxxx/simple_invites:latest
    ports:
      - "5000:5000"
    volumes:
      # Don't mount static directory, use the one built into the container
      - ./data/simple_invites:/data/simple_invites
    environment:
      - FLASK_ENV=production
      - APP_HOSTNAME=https://invites.ffw-windischletten.de  # Your production hostname
      - SECRET_KEY=dein_geheimer_schluessel
      - PDF_CLEANUP_MINUTES=30
      - DEBUG=True  # Enable debug mode to see more detailed errors
      - PYTHONUNBUFFERED=1  # Ensure Python output is not buffered