# Production docker-compose.yml für ffw-dockersetup
# Dieses File gehört in deinen ffw-dockersetup Ordner und ersetzt den simple_invites Service

services:
  simple_invites:
    image: bassdoxxx/simple_invites:latest
    container_name: simple_invites
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      # Persistente Daten (SQLite DB, Secret Key, etc.)
      - ./data/simple_invites:/app/instance
      - ./data/simple_invites/static:/app/app/static  # Für Uploads/statische Dateien
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SIMPLE_INVITES_SECRET_KEY:-your_secret_key_here}
      - APP_HOSTNAME=https://invites.ffw-windischletten.de
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - core_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 1m30s
      timeout: 10s
      retries: 3

networks:
  core_net:
    external: true
