services:
  simple_invites:
    image: bassdoxxx/simple_invites:latest
    ports:
      - "5000:5000"
    volumes:
      - ./app/static:/app/app/static
      - ./data/simple_invites:/data/simple_invites
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=dein_geheimer_schluessel
      - PDF_CLEANUP_MINUTES=30