"""Remove qr_code_path from Invite

Revision ID: b08ee25575d7
Revises: a08ee25575d6
Create Date: 2025-07-22 10:15:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b08ee25575d7'
down_revision = 'a08ee25575d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.drop_column('qr_code_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_code_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###
