"""Add contact details and QR code path

Revision ID: cef09c4481ff
Revises: add_contact_fields
Create Date: 2025-07-24 13:38:05.960253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cef09c4481ff'
down_revision = 'add_contact_fields'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ansprechpartner', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('strasse', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('plz', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('ort', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('telefon', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('qr_code_path', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.drop_column('qr_code_path')
        batch_op.drop_column('email')
        batch_op.drop_column('telefon')
        batch_op.drop_column('ort')
        batch_op.drop_column('plz')
        batch_op.drop_column('strasse')
        batch_op.drop_column('ansprechpartner')

    # ### end Alembic commands ###
